### ISSUE TITLE
YANG prefix unimplemented in CSDL

### ISSUE THREAD

**Issue by seiferteric** [DMTF/YANG-to-Redfish-Converter#15]
I am using the yang-plugin branch and pyang. In the output I don't see the prefix. For example, converting openconfig-interfaces.yang I would expect to see "oc-if" as the module name.

**Comment by tomasg2012** [comment]
From what I understand, only the xml attribute "Alias" is affected by the yang keyword 'prefix', and wouldn't affect the module name.  If this is related to imports, then imports should satisfy this nicely.

**Comment by tomasg2012** [comment]
Resolution with Network TF Meeting 8/24:  Alias is correct, however is not employed properly with yang type definitions that exist within the module namespace.  Double-check and correct this.

**Comment by tomasg2012** [comment]
Closed, Alias is included but not supported by CSDL's type resolution outside of references/imports.
