### ISSUE TITLE
Use proper pre-processor to remove C-style comments from YANG files

### ISSUE THREAD

**Issue by tomasg2012** [DMTF/YANG-to-Redfish-Converter#2]
Current process is indiscriminate of string syntax and will cause line breaks in strings that contain URLs.

**Comment by tomasg2012** [comment]
As of now, it works for http links but might break other kinds of links.

@jcleung5549 Would it be acceptable just to write in the README to suggest a utility or command line tool to strip comments?  Or should a stronger script be included with the repo, I've only been able to find perl scripts with the kind of power to remove comments consistently.  It's also an issue that YANG files themselves are not inherently C files, such that it may trip certain comment stripping logic.

**Comment by jcleung5549** [comment]
Yes, for now.   The wording in rfc6020 makes it assumes a C-style file.  If there are usages that violate this, then should there be escape characters in the offending YANG files?  The converter might just be more rigorous that other YANG tooling.  Please send (or attach) an offending YANG model.

From rfc6020, section 6.1.1 (Comments)
   Comments are C++ style.  A single line comment starts with "//" and ends at the end of the line.  A block comment is enclosed within "/*" and "*/".
