### ISSUE TITLE
Add proper support for RedfishYangExtensions

### ISSUE THREAD

**Issue by tomasg2012** [DMTF/YANG-to-Redfish-Converter#24]
Must implement ability to generate or add to RedfishYangExtensions xml file, based on the most basic Yang keywords/types and new created types.

- Consider generating from scratch, keeping a skeleton base line in code then to generate the resulting complementary file.
- Consider generating two different files, one for basic Yang definitions and another for Yang definitions by the converted .yang file
- We must be able to accommodate for all created 'yang' types: how does this work for multiple Yang to Csdl conversions?

**Comment by tomasg2012** [comment]
Resolution with Network TF Meeting 8/24:  migrate all specific yang file definitions to the xml files created by it, and test to see if the namespace chain resolves properly.  The only yang types that need inclusion in the YangExtensions file are yang types defined natively.

**Comment by jcleung5549** [comment]
Aug 2 meeting - agreed to close.
