### ISSUE TITLE
One CSDL file per module

### ISSUE THREAD

**Issue by jcleung5549** [DMTF/YANG-to-Redfish-Converter#34]
Currently, the converter generates multiple CSDL files per YANG module.  The Network Infrastructure TF would like the generator to create a single consolidated CSDL file per YANG module.

**Comment by tomasg2012** [comment]
This issue has been addressed in the latest commits, however, the combined file still adds all the "grouping" data that is normally removed when outputting to multiple files, and needs to be fixed.

**Comment by mraineri** [comment]
Resolved in latest PR
