### ISSUE TITLE
The conversion from OpenConfig YANG generates more CSDL files

### ISSUE THREAD

**Issue by jcleung5549** [DMTF/YANG-to-Redfish-Converter#36]
The conversion from OpenConfig YANG files generates far more CSDL files than from IETF YANG files (~50 vs 6 files)

Note:
1. The "top" structures are artifacts of the OpenConfig YANG constructs.  Entities/CSDLs don't need to create for them, since they never appear in a mockup as a Redfish resource.
2. Resolving #34, would collapses both the IETF files and OpenConfig files to one CSDL file, a piece.

**IETF CSDL files**
ietf_interfaces.interfaces_state.statistics_v1.xml
ietf_interfaces.interfaces_state_v1.xml
ietf_interfaces.interfaces_stateCollection_v1.xml
ietf_interfaces.interfaces_v1.xml
ietf_interfaces.interfacesCollection_v1.xml
ietf_interfaces_v1.xml

**OpenConfig CSDL files**
openconfig_interfaces.base_interface_ref_state.state_v1.xml
openconfig_interfaces.base_interface_ref_state_v1.xml
openconfig_interfaces.interface_common_config_v1.xml
openconfig_interfaces.interface_common_state_v1.xml
openconfig_interfaces.interface_counters_state.counters_v1.xml
openconfig_interfaces.interface_counters_state_v1.xml
openconfig_interfaces.interface_phys_config_v1.xml
openconfig_interfaces.interface_phys_holdtime_config_v1.xml
openconfig_interfaces.interface_phys_holdtime_state_v1.xml
openconfig_interfaces.interface_phys_holdtime_top.hold_time.config_v1.xml
openconfig_interfaces.interface_phys_holdtime_top.hold_time.state_v1.xml
openconfig_interfaces.interface_phys_holdtime_top.hold_time_v1.xml
openconfig_interfaces.interface_phys_holdtime_top_v1.xml
openconfig_interfaces.interface_ref.interface_ref.config_v1.xml
openconfig_interfaces.interface_ref.interface_ref.state_v1.xml
openconfig_interfaces.interface_ref.interface_ref_v1.xml
openconfig_interfaces.interface_ref_common_v1.xml
openconfig_interfaces.interface_ref_state.interface_ref.state_v1.xml
openconfig_interfaces.interface_ref_state.interface_ref_v1.xml
openconfig_interfaces.interface_ref_state_container.state_v1.xml
openconfig_interfaces.interface_ref_state_container_v1.xml
openconfig_interfaces.interface_ref_state_v1.xml
openconfig_interfaces.interface_ref_v1.xml
openconfig_interfaces.interfaces.interface.config_v1.xml
openconfig_interfaces.interfaces.interface.hold_time.config_v1.xml
openconfig_interfaces.interfaces.interface.hold_time.state_v1.xml
openconfig_interfaces.interfaces.interface.hold_time_v1.xml
openconfig_interfaces.interfaces.interface.state.counters_v1.xml
**openconfig_interfaces.interfaces.interface.state_v1.xml**
openconfig_interfaces.interfaces.interface.subinterfaces.subinterface.config_v1.xml
openconfig_interfaces.interfaces.interface.subinterfaces.subinterface.state.counters_v1.xml
openconfig_interfaces.interfaces.interface.subinterfaces.subinterface.state_v1.xml
openconfig_interfaces.interfaces.interface.subinterfaces.subinterface_v1.xml
openconfig_interfaces.interfaces.interface.subinterfaces.subinterfaceCollection_v1.xml
openconfig_interfaces.interfaces.interface.subinterfaces_v1.xml
openconfig_interfaces.interfaces.interface_v1.xml
openconfig_interfaces.interfaces.interfaceCollection_v1.xml
openconfig_interfaces.interfaces_top.interfaces.interface.config_v1.xml
openconfig_interfaces.interfaces_top.interfaces.interface.hold_time.config_v1.xml
openconfig_interfaces.interfaces_top.interfaces.interface.hold_time.state_v1.xml
openconfig_interfaces.interfaces_top.interfaces.interface.hold_time_v1.xml
openconfig_interfaces.interfaces_top.interfaces.interface.state.counters_v1.xml
openconfig_interfaces.interfaces_top.interfaces.interface.state_v1.xml
openconfig_interfaces.interfaces_top.interfaces.interface.subinterfaces.subinterface.config_v1.xml
openconfig_interfaces.interfaces_top.interfaces.interface.subinterfaces.subinterface.state.counters_v1.xml
openconfig_interfaces.interfaces_top.interfaces.interface.subinterfaces.subinterface.state_v1.xml
openconfig_interfaces.interfaces_top.interfaces.interface.subinterfaces.subinterface_v1.xml
openconfig_interfaces.interfaces_top.interfaces.interface.subinterfaces.subinterfaceCollection_v1.xml
openconfig_interfaces.interfaces_top.interfaces.interface.subinterfaces_v1.xml
openconfig_interfaces.interfaces_top.interfaces.interface_v1.xml
openconfig_interfaces.interfaces_top.interfaces.interfaceCollection_v1.xml
openconfig_interfaces.interfaces_top.interfaces_v1.xml
openconfig_interfaces.interfaces_top_v1.xml
**openconfig_interfaces.interfaces_v1.xml** (this should be a interfacesCollection)
openconfig_interfaces.sub_unnumbered_config_v1.xml
openconfig_interfaces.sub_unnumbered_state_v1.xml
openconfig_interfaces.sub_unnumbered_top.unnumbered.config_v1.xml
openconfig_interfaces.sub_unnumbered_top.unnumbered.interface_ref.config_v1.xml
openconfig_interfaces.sub_unnumbered_top.unnumbered.interface_ref.state_v1.xml
openconfig_interfaces.sub_unnumbered_top.unnumbered.interface_ref_v1.xml
openconfig_interfaces.sub_unnumbered_top.unnumbered.state_v1.xml
openconfig_interfaces.sub_unnumbered_top.unnumbered_v1.xml
openconfig_interfaces.sub_unnumbered_top_v1.xml
openconfig_interfaces.subinterfaces_config_v1.xml
openconfig_interfaces.subinterfaces_state.counters_v1.xml
openconfig_interfaces.subinterfaces_state_v1.xml
openconfig_interfaces.subinterfaces_top.subinterfaces.subinterface.config_v1.xml
openconfig_interfaces.subinterfaces_top.subinterfaces.subinterface.state.counters_v1.xml
openconfig_interfaces.subinterfaces_top.subinterfaces.subinterface.state_v1.xml
openconfig_interfaces.subinterfaces_top.subinterfaces.subinterface_v1.xml
openconfig_interfaces.subinterfaces_top.subinterfaces.subinterfaceCollection_v1.xml
openconfig_interfaces.subinterfaces_top.subinterfaces_v1.xml
openconfig_interfaces.subinterfaces_top_v1.xml
**openconfig_interfaces_v1.xml**

**Comment by mraineri** [comment]
Resolved in latest PR
