### ISSUE TITLE
Unclear how to reference generated CSDL file

### ISSUE THREAD

**Issue by jcleung5549** [DMTF/YANG-to-Redfish-Converter#40]
[openconfig_acl_v1.xml.txt](https://github.com/DMTF/YANG-to-Redfish-Converter/files/3024552/openconfig_acl_v1.xml.txt)

The  CSDL generated from openconfig_acl.yang contains the following fragments for acl_sets and acl_set.  The schema look empty.  How does a mockup reference this to resolve the property definitions?

		<Schema xmlns="http://docs.oasis-open.org/odata/ns/edm" Namespace="openconfig_acl.acl_set_top.acl_sets.acl_set">
			<Annotation Term="Redfish.OwningEntity" String="DMTF"/>
			<EntityType Name="acl_set" Abstract="true" BaseType="Resource.v1_0_0.Resource">
				<Annotation Term="OData.Description" String="Parameters for acl_set."/>
				<Annotation Term="OData.LongDescription" String="Parameters for acl_set."/>
				<Annotation Term="Capabilities.InsertRestrictions">
					<Record>
						<PropertyValue Property="Insertable" Bool="false"/>
					</Record>
				</Annotation>
				<Annotation Term="Capabilities.UpdateRestrictions">
					<Record>
						<PropertyValue Property="Updatable" Bool="false"/>
					</Record>
				</Annotation>
				<Annotation Term="Capabilities.DeleteRestrictions">
					<Record>
						<PropertyValue Property="Deletable" Bool="false"/>
					</Record>
				</Annotation>
			</EntityType>
		</Schema>
		<Schema xmlns="http://docs.oasis-open.org/odata/ns/edm" Namespace="openconfig_acl.acl_set_top.acl_sets">
			<Annotation Term="Redfish.OwningEntity" String="DMTF"/>
			<EntityType Name="acl_sets" Abstract="true" BaseType="Resource.v1_0_0.Resource">
				<Annotation Term="OData.Description" String="Parameters for acl_sets."/>
				<Annotation Term="OData.LongDescription" String="Parameters for acl_sets."/>
				<Annotation Term="Capabilities.InsertRestrictions">
					<Record>
						<PropertyValue Property="Insertable" Bool="false"/>
					</Record>
				</Annotation>
				<Annotation Term="Capabilities.UpdateRestrictions">
					<Record>
						<PropertyValue Property="Updatable" Bool="false"/>
					</Record>
				</Annotation>
				<Annotation Term="Capabilities.DeleteRestrictions">
					<Record>
						<PropertyValue Property="Deletable" Bool="false"/>
					</Record>
				</Annotation>
			</EntityType>
		</Schema>

**Comment by tomasg2012** [comment]
These are not the v1_0_0 version namespace of the containers, just the base schema of it. 

```
<Schema xmlns="http://docs.oasis-open.org/odata/ns/edm" Namespace="openconfig_acl.acl_set_top.acl_sets.acl_set.v1_0_0">
			<Annotation Term="Redfish.OwningEntity" String="DMTF"/>
			<Annotation Term="Redfish.Release" String="TBD"/>
			<Annotation Term="RedfishYang.key" String="name type"/>
			<Annotation Term="OData.Description" String="List of ACL sets, each comprising of a list of ACL entries."/>
			<Annotation Term="OData.LongDescription" String="List of ACL sets, each comprising of a list of ACL entries."/>
			<EntityType Name="acl_set" BaseType="openconfig_acl.acl_set_top.acl_sets.acl_set.acl_set">
				<Annotation Term="RedfishYang.NodeType" EnumMember="RedfishYang.NodeTypes/list"/>
				<Property Name="name" Type="Edm.String">
					<Annotation Term="RedfishYang.NodeType" EnumMember="RedfishYang.NodeTypes/leaf"/>
					<Annotation Term="RedfishYang.YangType" EnumMember="RedfishYang.YangTypes/leafref">
						<Annotation Term="RedfishYang.path" String="../config/name"/>
					</Annotation>
					<Annotation Term="OData.Description" String="Reference to the name list key."/>
					<Annotation Term="OData.LongDescription" String="Reference to the name list key."/>
					<Annotation Term="OData.Permissions" EnumMember="OData.Permission/Read"/>
				</Property>
				<Property Name="type" Type="Edm.String">
					<Annotation Term="RedfishYang.NodeType" EnumMember="RedfishYang.NodeTypes/leaf"/>
					<Annotation Term="RedfishYang.YangType" EnumMember="RedfishYang.YangTypes/leafref">
						<Annotation Term="RedfishYang.path" String="../config/type"/>
					</Annotation>
					<Annotation Term="OData.Description" String="Reference to the type list key."/>
					<Annotation Term="OData.LongDescription" String="Reference to the type list key."/>
					<Annotation Term="OData.Permissions" EnumMember="OData.Permission/Read"/>
				</Property>
				<NavigationProperty Name="configContainer" Type="config.config" ContainsTarget="true">
					<Annotation Term="OData.Permissions" EnumMember="OData.Permissions/Read"/>
					<Annotation Term="OData.Description" String="Navigation property that points to a resource of config."/>
					<Annotation Term="OData.LongDescription" String="Automatically generated."/>
					<Annotation Term="OData.AutoExpandReferences"/>
				</NavigationProperty>
				<NavigationProperty Name="stateContainer" Type="state.state" ContainsTarget="true">
					<Annotation Term="OData.Permissions" EnumMember="OData.Permissions/Read"/>
					<Annotation Term="OData.Description" String="Navigation property that points to a resource of state."/>
					<Annotation Term="OData.LongDescription" String="Automatically generated."/>
					<Annotation Term="OData.AutoExpandReferences"/>
				</NavigationProperty>
				<NavigationProperty Name="acl_entriesContainer" Type="acl_entries.acl_entries" ContainsTarget="true">
					<Annotation Term="OData.Permissions" EnumMember="OData.Permissions/Read"/>
					<Annotation Term="OData.Description" String="Navigation property that points to a resource of acl_entries."/>
					<Annotation Term="OData.LongDescription" String="Automatically generated."/>
					<Annotation Term="OData.AutoExpandReferences"/>
				</NavigationProperty>
			</EntityType>
		</Schema>
```

@mraineri is having an unversioned namespace required in all this or should the above generated just point directly to Resource.v1_0_0.Resource.  i.e. remove `BaseType="openconfig_acl.acl_set_top.acl_sets.acl_set.acl_set">` and replace with `<BaseType="Resource.v1_0_0.Resource">`

**Comment by mraineri** [comment]
There will need to be both versioned and unversioned namespaces. For example:

The unversioned `openconfig_acl.acl_set_top.acl_sets` namespace will need to exist and contain the base entity type also named `openconfig_acl.acl_set_top.acl_sets`, which inherits from `Resource.v1_0_0.Resource`.

There will also need to be a `openconfig_acl.acl_set_top.acl_sets.v1_0_0` namespace, which contains the entity `openconfig_acl.acl_set_top.acl_sets.v1_0_0`, which inherits from `openconfig_acl.acl_set_top.acl_sets.openconfig_acl.acl_set_top.acl_sets`.

**Comment by jcleung5549** [comment]
Using the branch yang-2019, this is no longer an issue.
