### ISSUE TITLE
CSDLs are  missing an Action

### ISSUE THREAD

**Issue by jcleung5549** [DMTF/YANG-to-Redfish-Converter#46]
The generated CSDL files needs a Action element.  Below is a typical message.

```
  3) CSDL Tests
       metadata/ietf_inet_types_v1.xml
         All EntityType defintions have Actions:
     Error: Entity Type "ietf_inet_types" does not contain an Action
      at entityTypesHaveActions (node_modules\redfishrepotest\csdl-syntax-test.js:801:13)
      at Context.it (node_modules\redfishrepotest\csdl-syntax-test.js:110:59)
```

**Comment by mraineri** [comment]
Is this something we want to whitelist in the Travis tests? I thought one of the early decisions was to not produce actions for YANG-based resources, and only put actions at the "NetworkDevice" level.

**Comment by jcleung5549** [comment]
Yes, let's whitelist.

**Comment by mraineri** [comment]
A check for the YANG whitelist will need to be made in the "entityTypesHaveActions" function of csdl-syntax-test.js.

**Comment by jcleung5549** [comment]
Using branch yang-2019 and the latest update to csdl-syntax-test.js, this Travis error is gone.
