### ISSUE TITLE
RedfishYangExtension missing OwningEntity and Release annotations

### ISSUE THREAD

**Issue by jcleung5549** [DMTF/YANG-to-Redfish-Converter#54]
The Travis messages

1) CSDL Tests
       metadata/RedfishYangExtensions_v1.xml
         All namespaces have OwningEntity:
     Error: Namespace RedfishYangExtensions.v1_0_0 lacks OwningEntity!
      at schemaOwningEntityCheck (node_modules/redfishrepotest/csdl-syntax-test.js:1618:15)
      at Context.<anonymous> (node_modules/redfishrepotest/csdl-syntax-test.js:164:55)
      at processImmediate (internal/timers.js:461:21)
  2) CSDL Tests
       metadata/RedfishYangExtensions_v1.xml
         All versioned, non-errata namespaces have Release:
     Error: Namespace RedfishYangExtensions.v1_0_0 lacks Release term!
      at schemaReleaseCheck (node_modules/redfishrepotest/csdl-syntax-test.js:1643:15)
      at Context.<anonymous> (node_modules/redfishrepotest/csdl-syntax-test.js:174:72)
      at processImmediate (internal/timers.js:461:21)

**Comment by jcleung5549** [comment]
Added them manually.  This eliminated the message regarding the Release annotation.  Still not happy with the OwningEntity.

    <Schema xmlns="http://docs.oasis-open.org/odata/ns/edm" Namespace="RedfishYangExtensions.v1_0_0">
      <Annotation Term="Redfish.OwningEntity" String="DMTF"/>
      <Annotation Term="Redfish.Release" String="1.0"/>

**Comment by jcleung5549** [comment]
The OeningEntity annotation in RedfishExtensions_v1.xml has a different form.

      <Annotation Term="RedfishExtensions.v1_0_0.OwningEntity" String="DMTF"/>

**Comment by jcleung5549** [comment]
Looks like the issue are in csdl-syntax-test.js

```
const NamespacesWithoutReleaseTerm = ['RedfishExtensions.v1_0_0', 'Validation.v1_0_0', 'RedfishError.v1_0_0', 'Schedule.v1_0_0', 'Schedule.v1_1_0' ];

function schemaOwningEntityCheck(csdl) {
  let schemas = CSDL.search(csdl, 'Schema');
  for(let i = 0; i < schemas.length; i++) {
    let owningEntity = CSDL.search(schemas[i], 'Annotation', 'Redfish.OwningEntity');
    if(owningEntity.length === 0) {
      let owningEntity = CSDL.search(schemas[i], 'Annotation', 'RedfishExtensions.v1_0_0.OwningEntity');
      if(owningEntity.length === 0) {
        throw new Error('Namespace '+schemas[i]._Name+' lacks OwningEntity!');
      }
    }
  }
}
```

**Comment by mraineri** [comment]
It's different in RedfishExtensions_v1.xml because of the lack of aliasing in that file. All other files pull in "RedfishExtensions.v1_0_0" and alias it as "Redfish", but local aliasing does not seem possible.

**Comment by jcleung5549** [comment]
Thanks for the guidance.  I just have one error regarding OwningEntity.

```
1) CSDL Tests
       metadata/RedfishYangExtensions_v1.xml
         All Annotation Terms are valid:
     Error: Unable to locate annotation term "Redfish.OwningEntity"
      at checkAnnotationTerms (node_modules/redfishrepotest/csdl-syntax-test.js:651:13)
      at Context.<anonymous> (node_modules/redfishrepotest/csdl-syntax-test.js:152:51)
      at processImmediate (internal/timers.js:461:21)
```
But, the annotation is there

```
    <Schema xmlns="http://docs.oasis-open.org/odata/ns/edm" Namespace="RedfishYangExtensions.v1_0_0">
      <Annotation Term="Redfish.OwningEntity" String="DMTF"/>
      <Annotation Term="Redfish.Release" String="1.0"/>
```

**Comment by mraineri** [comment]
It might be because it's lacking the inclusion of the RedfishExtensions file; try adding:

```
  <edmx:Reference Uri="http://redfish.dmtf.org/schemas/v1/RedfishExtensions_v1.xml">
    <edmx:Include Namespace="RedfishExtensions.v1_0_0" Alias="Redfish"/>
  </edmx:Reference>
```

**Comment by jcleung5549** [comment]
Bingo! 

Thanks. Your guidance is better than my flailing.

**Comment by jcleung5549** [comment]
Resolved
